server:
  port: ${SERVER_PORT:8089}
spring:
  application:
    name: application-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5438/applicationdb}
    username: ${DB_USERNAME:app}
    password: ${DB_PASSWORD:app}
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
security:
  jwt:
    secret: ${SECURITY_JWT_SECRET:2q8pKX2a7o1X6jO0Vqkq0+U2YQj9tS8R4qv8x9w1e+M=}
  internal-api-key: ${INTERNAL_API_KEY:changeme}
kyc:
  base-url: ${KYC_BASE_URL:http://kyc-service:8086}
underwriting:
  base-url: ${UW_BASE_URL:http://underwriting-service:8087}
pricing:
  base-url: ${PRICING_BASE_URL:http://product-pricing-service:8088}

