version: "3.8"
services:
  camunda-postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: camunda
      POSTGRES_USER: camunda
      POSTGRES_PASSWORD: camunda
    ports:
      - "5443:5432"
    volumes:
      - camunda_pgdata:/var/lib/postgresql/data

  camunda-platform:
    image: camunda/camunda-bpm-platform:7.21.0
    depends_on:
      - camunda-postgres
    environment:
      DB_DRIVER: org.postgresql.Driver
      DB_URL: jdbc:postgresql://camunda-postgres:5432/camunda
      DB_USERNAME: camunda
      DB_PASSWORD: camunda
    ports:
      - "18081:8080"

  bpm-service:
    depends_on:
      - camunda-platform

volumes:
  camunda_pgdata:
