global:
  scrape_interval: 15s
rule_files:
  - /etc/prometheus/alerts.yml
  - /etc/prometheus/slo.yml
scrape_configs:
  - job_name: 'spring'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'auth-service:8081'
          - 'inventory-service:8082'
          - 'procurement-service:8083'
          - 'reports-service:8084'
          - 'customer-service:8085'
          - 'kyc-service:8086'
          - 'underwriting-service:8087'
          - 'product-pricing-service:8088'
          - 'application-service:8089'
          - 'agreement-service:8090'
          - 'billing-service:8091'
          - 'payments-service:8092'
          - 'gateway-service:8080'
          - 'schedule-service:8093'
          - 'edocs-service:8094'
          - 'bpm-service:8095'
          - 'accounting-service:8096'
