apiVersion: v1
kind: Secret
metadata:
  name: crp-shared
  namespace: crp
type: Opaque
data:
  jwt-secret: MmE4cEtYMmE3bzFYNmpPMFZxa3EwK1UyWVFqOXRTOFI0cXZ4OXcxZS9NPQ==
  internal-api-key: Y2hhbmdlbWU=

