server:
  port: ${SERVER_PORT:8095}
spring:
  application:
    name: bpm-service
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
security:
  internal-api-key: ${INTERNAL_API_KEY:changeme}

crp:
  security:
    jwt:
      enforce-audience: true
kyc:
  base-url: ${KYC_BASE_URL:http://kyc-service:8086}
underwriting:
  base-url: ${UW_BASE_URL:http://underwriting-service:8087}
pricing:
  base-url: ${PRICING_BASE_URL:http://product-pricing-service:8088}
