server:
  port: ${SERVER_PORT:8083}

spring:
  application:
    name: procurement-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5435/procurementdb}
    username: ${DB_USERNAME:proc}
    password: ${DB_PASSWORD:proc}
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:kafka:9092}
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI:${SECURITY_JWT_ISSUER:http://auth-service:8081}}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

security:
  internal-api-key: ${INTERNAL_API_KEY:changeme}

crp:
  security:
    jwt:
      enforce-audience: true
