server:
  port: ${SERVER_PORT:8091}
spring:
  application:
    name: billing-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5440/billingdb}
    username: ${DB_USERNAME:billing}
    password: ${DB_PASSWORD:billing}
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:kafka:9092}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI:${SECURITY_JWT_ISSUER:http://auth-service:8081}}
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
security:
  jwt:
    secret: ${SECURITY_JWT_SECRET:2q8pKX2a7o1X6jO0Vqkq0+U2YQj9tS8R4qv8x9w1e+M=}
  internal-api-key: ${INTERNAL_API_KEY:changeme}
schedule:
  base-url: ${SCHEDULE_BASE_URL:http://schedule-service:8093}
crp:
  security:
    jwt:
      enforce-audience: true
